from typing import Protocol

class Testable(Protocol):
    def go(self, src): ...
    def fails(self, src): ...
    def expanded(self, src): ...
    def printed(self, src): ...
    def assertEqual(self, first, second, msg=...): ...
    def assertTrue(self, expr, msg=...): ...
    def assertFalse(self, expr, msg=...): ...
